### ISSUE TITLE
Yellow dropdown box for autocompletion when there is no value selected.

### ISSUE THREAD

**Issue by gobijan** [ohsufresh/emerald#1]
<img width="975" alt="Bildschirmfoto 2020-08-07 um 22 58 30" src="https://user-images.githubusercontent.com/49339/89687997-894de680-d901-11ea-9785-a485d3523efe.png">

My autocompletion box shows up automatically when I type and as soon as I cycle through options it gets fixed but looks otherwise like shown in the screenshot...

**Comment by adebesin** [comment]
will look to fix in next release

**Comment by greenlaw110** [comment]
Any schedule for the next release?

**Comment by franciskim** [comment]
A fix would be much appreciated! Such a good theme 👍 👍

**Comment by adebesin** [comment]
Yep, sorry guys i will look push the new updates within the next week. Theres a whole bunch of other fixes as well 👍

**Comment by franciskim** [comment]
@ohsufresh any updates? :) Also, is there a way to sponsor this project?

**Comment by ohsufresh** [comment]
The issue with the yellow popup has been resolved and submitted sorry about the delay been kinda busy with work. The latest release will be available as soon as JetBrains have verified it (usually takes 24 hours). Also I will set up sponsoring. Feel free to donate 👍
